apiVersion: apps/v1
kind: Deployment

metadata:
  name: crewmeister-app

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: crewmeister-app

  template:
    metadata:
      labels:
        app: crewmeister-app

    spec:
      containers:
        - name: crewmeister-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          ports:
            - containerPort: 8080

          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/challenge?createDatabaseIfNotExist=true

            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.mysql.username }}

            - name: SPRING_DATASOURCE_PASSWORD
              value: {{ .Values.mysql.password }}